name: 'Page Insights Action'
description: |
    Run Google Page Insights on a list of URLs or a sitemap.
    Depending on your thresholds, the action will pass or fail.
    Requires a Google Page Insights API key.

inputs:
  urls:
    description: 'URLs to audit (separated by new lines)'
  device:
    description: 'Device to emulate (mobile/desktop)'
    default: 'mobile'
    required: true
  page_insights_key:
    description: 'Google Page Insights API key'
    required: true
  performance_threshold:
    description: 'Performance threshold'
  seo_threshold:
    description: 'SEO threshold'
  accessibility_threshold:
    description: 'Accessibility threshold'
  best_practices_threshold:
    description: 'Best practices threshold'
  mode:
    description: 'Mode to run the audit in'
    default: 'SITEMAP'
    required: true
  sitemap_url:
    description: 'Sitemap URL'
outputs:
  scores:
    description: 'Scores for each URL'
  average_scores:
    description: 'Average scores for all URLs'
runs:
  using: 'node16'
  main: 'dist/index.js'