name: 'Lighthouse Action'
description: 'Run Lighthouse audit'
inputs:
  urls:
    description: 'URLs to audit'
    required: true
  device:
    description: 'Device to emulate (mobile/desktop)'
    default: 'mobile'
  page_insights_key:
    description: 'Google Page Insights API key'
    required: true
  performance_threshold:
    description: 'Performance threshold'
  seo_threshold:
    description: 'SEO threshold'
  accessibility_threshold:
    description: 'Accessibility threshold'
  best_practices_threshold:
    description: 'Best practices threshold'
runs:
  using: 'node16'
  main: 'dist/index.js'