name: 'Lighthouse Action'
description: 'Run Lighthouse audit'
inputs:
  url:
    description: 'URL to audit'
    required: true
  threshold:
    description: 'Performance score threshold'
    default: '90'
  device:
    description: 'Device to emulate (mobile/desktop)'
    default: 'mobile'
runs:
  using: 'node16'
  main: 'dist/index.js'