name: 'Lighthouse Action'
description: 'Run Lighthouse audit'
inputs:
  urls:
    description: 'URLs to audit'
    required: true
  threshold:
    description: 'Performance score threshold'
    default: '90'
  device:
    description: 'Device to emulate (mobile/desktop)'
    default: 'mobile'
  page_insights_key:
    description: 'Google Page Insights API key'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'