name: PageInsights CI

on:
  push:
    branches:
      - main
      - master
      - development
      - feature/**

    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
      - 'dist/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      # Test the action using itself
      - name: Run PageInsights Action (Manual)
        uses: ./
        with:
          device: 'DESKTOP'
          page_insights_key: ${{ secrets.PAGE_INSIGHTS_KEY }}
          performance_threshold: '75'
          seo_threshold: '75'
          accessibility_threshold: '75'
          best_practices_threshold: '75'
          mode: 'MANUAL'
          urls: |
            https://leothelegion.net
            https://leothelegion.net/blog
          show_table_in_summary: true

      # Test the action using itself
      - name: Run PageInsights Action (Manual - PS)
        uses: ./
        with:
          device: 'DESKTOP'
          page_insights_key: ${{ secrets.PAGE_INSIGHTS_KEY }}
          performance_threshold: '75'
          seo_threshold: '75'
          mode: 'MANUAL'
          urls: |
            https://leothelegion.net
            https://leothelegion.net/blog
          show_table_in_summary: true
      
      # Test the action using itself
      - name: Run PageInsights Action (Manual - AB)
        uses: ./
        with:
          device: 'DESKTOP'
          page_insights_key: ${{ secrets.PAGE_INSIGHTS_KEY }}
          accessibility_threshold: '75'
          best_practices_threshold: '75'
          mode: 'MANUAL'
          urls: |
            https://leothelegion.net
            https://leothelegion.net/blog
          show_table_in_summary: true

      # Test the action using itself
      - name: Run PageInsights Action (Sitemap)
        uses: ./
        with:
          device: 'DESKTOP'
          page_insights_key: ${{ secrets.PAGE_INSIGHTS_KEY }}
          performance_threshold: '75'
          seo_threshold: '75'
          accessibility_threshold: '75'
          best_practices_threshold: '75'
          mode: 'SITEMAP'
          sitemap_url: 'https://leothelegion.net/sitemap-index.xml'

  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Generate Hash on dist 
        id: hash
        run: |
          echo "Hashing dist files"
          HASH=$(find dist -type f -exec sha256sum {} \; | sort | sha256sum | cut -d' ' -f1)
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Build
        run: npm run build

      - name: Check if dist has changed
        id: check_dist
        run: |
          HASH=$(find dist -type f -exec sha256sum {} \; | sort | sha256sum | cut -d' ' -f1)
          if [ "$HASH" = "$(grep hash $GITHUB_EVENT_PATH | cut -d'=' -f2)" ]; then
            echo "hasChanged=false" >> $GITHUB_OUTPUT
            echo "No changes in dist"
          else
            echo "hasChanged=true" >> $GITHUB_OUTPUT
            echo "Changes detected in dist"
          fi

      - name: Configure Git
        if: ${{ steps.check_dist.outputs.hasChanged == 'true' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Get version from package.json
        id: get_version
        run: echo "::set-output name=version::$(node -p -e "require('./package.json').version")"

      - name: Commit dist
        if: ${{ steps.check_dist.outputs.hasChanged == 'true' }}
        run: |
          git add dist -f
          git commit -m "chore: update dist for version ${{ github.ref_name }}"
          git push origin HEAD:main

      - name: Create Release
        if: ${{ steps.check_dist.outputs.hasChanged == 'true' }}
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          draft: true
          prerelease: false
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}