name: PageInsights CI

on:
  push:
    branches:
      - main
      - master
      - development
      - feature/**

    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      # Test the action using itself
      - name: Run PageInsights Action (Manual)
        uses: ./
        with:
          device: 'DESKTOP'
          page_insights_key: ${{ secrets.PAGE_INSIGHTS_KEY }}
          performance_threshold: '75'
          seo_threshold: '75'
          accessibility_threshold: '75'
          best_practices_threshold: '75'
          mode: 'MANUAL'
          urls: |
            https://leothelegion.net
            https://leothelegion.net/blog
          show_table_in_summary: true

      # Test the action using itself
      - name: Run PageInsights Action (Manual - PS)
        uses: ./
        with:
          device: 'DESKTOP'
          page_insights_key: ${{ secrets.PAGE_INSIGHTS_KEY }}
          performance_threshold: '75'
          seo_threshold: '75'
          mode: 'MANUAL'
          urls: |
            https://leothelegion.net
            https://leothelegion.net/blog
          show_table_in_summary: true
      
      # Test the action using itself
      - name: Run PageInsights Action (Manual - AB)
        uses: ./
        with:
          device: 'DESKTOP'
          page_insights_key: ${{ secrets.PAGE_INSIGHTS_KEY }}
          accessibility_threshold: '75'
          best_practices_threshold: '75'
          mode: 'MANUAL'
          urls: |
            https://leothelegion.net
            https://leothelegion.net/blog
          show_table_in_summary: true

      # Test the action using itself
      - name: Run PageInsights Action (Sitemap)
        uses: ./
        with:
          device: 'DESKTOP'
          page_insights_key: ${{ secrets.PAGE_INSIGHTS_KEY }}
          performance_threshold: '75'
          seo_threshold: '75'
          accessibility_threshold: '75'
          best_practices_threshold: '75'
          mode: 'SITEMAP'
          sitemap_url: 'https://leothelegion.net/sitemap-index.xml'

  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Get version from package.json
        id: get_version
        run: echo "::set-output name=version::$(node -p -e "require('./package.json').version")"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist
          asset_name: dist.zip
          asset_content_type: application/zip