name: PageInsights CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      # Test the action using itself
      - name: Run PageInsights Action
        uses: ./
        with:
          urls: 'https://leothelegion.net https://leothelegion.net/blog' # Test multiple URLs
          threshold: '90'
          device: 'mobile'
          page_insights_key: ${{ secrets.PAGE_INSIGHTS_KEY }}
      
      # Optional: Add another test case
      - name: Run PageInsights Action (Desktop)
        uses: ./
        with:
          urls: 'https://leothelegion.net https://leothelegion.net/blog' # Test multiple URLs
          threshold: '90'
          device: 'desktop'
          page_insights_key: ${{ secrets.PAGE_INSIGHTS_KEY }}